# Generated by Django 3.2.4 on 2022-02-19 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_shopuserprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopuserprofile',
            old_name='aboutMe',
            new_name='about_me',
        ),
    ]
